## Part- 1

In [1]:
import torch

In [4]:
def activation(x):
    return 1/(1+torch.exp(-x))



In [5]:
torch.manual_seed(7) #generates data

#generates 5 random vars, size is 1 row and 5 columns
features = torch.randn((1,5))

#generate weights with same shape as features
weights = torch.randn_like(features)

#define a bias term
bias = torch.randn((1,1))

In [6]:
#First, calculate output using weights and bias tensors

y = activation((features*weights).sum() + bias)
print(y)

tensor([[0.1595]])


In [10]:
# Second, calculate output of network using matrix multiplication

y = activation(torch.mm(features, weights.view(5,1)) + bias)
print(y)

tensor([[0.1595]])


### Adding more layers

In [11]:
#generate more data
torch.manual_seed(7)

#features are 3 random normal variables
features = torch.randn((1,3))

#define the size of each layer in the network
n_input = features.shape[1] #must match number of input features
n_hidden = 2
n_output = 1

#weights for input to hidden layer
w1 = torch.randn(n_input,n_hidden)

#weights for hidden to output layer
w2 = torch.randn(n_hidden, n_output)

#bias terms for both layers
b1 = torch.randn((1, n_hidden))
b2 = torch.randn((1, n_output))

In [12]:
h = activation(torch.mm(features, w1) + b1)
output = activation(torch.mm(h, w2) + b2)
print(output)

tensor([[0.3171]])


## Part- 2